node {
    stage 'Clone the project'
    git 'https://github.com/ggera/k8sApps.git'
   
    dir('geralab s-jenkins-pipeline') {
        stage("Build") {

                    stage("Staging") {
                        sh "../docker/build-image.sh"
                    }
                }

        stage("Deployment") {

            stage("Staging") {
                sh "../k8s/deploy.sh"
            }
        }
    }
}