
image:
  repository: "hub.docker.com/geralabs-cr"
  pullPolicy: "IfNotPresent"
  tag: "latest"


replicaCount: 1

profileName: "dev"

javaOpts: "-XX:+UseParallelOldGC -XX:ParallelGCThreads=8 -ms512M -mx1024M"
resources:
  limits:
    cpu: "4"
    memory: "3Gi"
  requests:
    cpu: "100m"
    memory: "512Mi"

rollingUpdate:
  maxUnavailable: 40%

# Nginx ingress settings
controller:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
  service:
    enableHttp: true
  stats:
    enabled: true
  metrics:
    enabled: true

# Ingress settigns
ingress:
  enabled: true
  name: geralabsapp1
  rules:
  - host: gera-labs.com
    http:
      paths:
      - path: /app1
        backend:
          serviceName: geralabsapp1
          servicePort: 9090
      - path: /app2
          backend:
            serviceName: geralabsapp2
            servicePort: 8080