
image:
  repository: "hub.docker.com/geralabs-cr/geralabs-app2"
  pullPolicy: "IfNotPresent"
  tag: "latest"


replicaCount: 1

profileName: "dev"

javaOpts: "-XX:+UseParallelOldGC -XX:ParallelGCThreads=8 -ms512M -mx1024M"
resources:
  limits:
    cpu: "4"
    memory: "3Gi"
  requests:
    cpu: "100m"
    memory: "512Mi"

rollingUpdate:
  maxUnavailable: 40%

imageCredentials:
  registry: hub.docker.com/geralabs-cr
  username: gerawork
  password: changeit
