---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geralabsapp1
  labels:
    app: geralabsapp1
    version: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 40%
  selector:
    matchLabels:
      app: geralabsapp1
  template:
    metadata:
      labels:
        app: geralabsapp1
    spec:
      containers:
        - name: geralabs-app1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /app1
              port: 9090
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /app1
              port: 9090
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          #Pass Environment Variables to Container
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "{{ .Values.profileName }}"
          - name: JAVA_OPTS
            value: "{{ .Values.javaOpts }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: geralabs-cr
      restartPolicy: Always
      dnsPolicy: ClusterFirst

status: {}