apiVersion: v1
kind: Service
metadata:
  name: geralabsapp1
spec:
  selector:
    app: geralabsapp1
  ports:
  - name: "http"
    protocol: TCP
    port: 9090
    targetPort: 9090
status:
  loadBalancer: {}