apiVersion: v1
kind: Service
metadata:
  name: geralabsapp2
spec:
  selector:
    app: geralabsapp2
  ports:
  - name: "http"
    protocol: TCP
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}